# Path to your oh-my-zsh installation.
source ~/.antigen.zsh
antigen use oh-my-zsh
# Common exports
export EDITOR='nvim'
export PATH="$HOME/bin":$PATH
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.nvm/node_modules/.bin:$PATH"
# Always use nvm for node
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Antigen stuff
#antigen theme geometry-zsh/geometry
antigen bundle git
antigen bundle pip
#antigen bundle npm
#antigen bundle z
#antigen bundle fasd
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
# Theme
#antigen theme geometry-zsh/geometry
#antigen theme denysdovhan/spaceship-prompt
antigen apply
#source ~/.oh-my-zsh/custom/themes/jovial.zsh-theme
#eval "$(fasd --init auto)"
eval "$(starship init zsh)"
source ~/.config/zsh/aliases
