# Path to your oh-my-zsh installation.
source ~/.antigen.zsh
antigen use oh-my-zsh
# Common exports
export EDITOR='nvim'
export PATH="$HOME/bin":$PATH
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.nvm/node_modules/.bin:$PATH"
#export PATH="$HOME/.cargo/bin":$PATH
# conda
if [ -d "$HOME/anaconda3/bin" ] ; then
    PATH="$HOME/anaconda3/bin:$PATH"
fi
# Always use nvm for node
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/home/r0b0t/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "/home/r0b0t/anaconda3/etc/profile.d/conda.sh" ]; then
#         . "/home/r0b0t/anaconda3/etc/profile.d/conda.sh"
#     else
#         export PATH="/home/r0b0t/anaconda3/bin:$PATH"
#     fi
# fi
# unset __conda_setup

# Antigen stuff
#antigen theme geometry-zsh/geometry
antigen bundle git
antigen bundle pip
#antigen bundle npm
#antigen bundle z
#antigen bundle fasd
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
# Theme
#antigen theme geometry-zsh/geometry
#antigen theme denysdovhan/spaceship-prompt
antigen apply
#source ~/.oh-my-zsh/custom/themes/jovial.zsh-theme
#eval "$(fasd --init auto)"
eval "$(starship init zsh)"
source ~/.config/zsh/aliases
