config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  f_keybindings.json:
    src: config/Code - Insiders/User/keybindings.json
    dst: ~/.config/Code - Insiders/User/keybindings.json
  f_settings.json:
    src: config/Code - Insiders/User/settings.json
    dst: ~/.config/Code - Insiders/User/settings.json
  f_preferences.sublime-settings:
    src: config/sublime-text-3/Packages/User/Preferences.sublime-settings
    dst: ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
  f_default-(linux).sublime-keymap:
    src: config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap
    dst: ~/.config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap
  f_package-control.sublime-settings:
    src: config/sublime-text-3/Packages/User/Package Control.sublime-settings
    dst: ~/.config/sublime-text-3/Packages/User/Package Control.sublime-settings
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_icons:
    src: local/share/icons
    dst: ~/.local/share/icons
  f_zshrc_1:
    src: zshrc
    dst: ~/.zshrc
  d_config_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_xrdb:
    src: xrdb
    dst: ~/.xrdb
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_config.fish:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
  d_config_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_config_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_redshift:
    src: config/redshift
    dst: ~/.config/redshift
  d_config_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_config_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_mpd:
    src: config/mpd
    dst: ~/.config/mpd
  d_ncmpcpp:
    src: config/ncmpcpp
    dst: ~/.config/ncmpcpp
  d_config_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_scripts:
    src: Scripts
    dst: ~/Scripts
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_config_i3:
    src: config/i3
    dst: ~/.config/i3
profiles:
  horizon:
    dotfiles:
    - f_zshrc
    - d_i3
    - d_polybar
    - d_zsh
    - d_sxhkd
    - d_kitty
    - d_alacritty
    - f_keybindings.json
    - f_settings.json
    - f_preferences.sublime-settings
    - f_default-(linux).sublime-keymap
    - f_package-control.sublime-settings
    - d_rofi
    - f_starship.toml
    - d_icons
  manjaro:
    dotfiles:
    - f_zshrc_1
    - d_config_kitty
    - d_xrdb
    - f_xresources
    - f_config.fish
    - d_config_zsh
    - f_tmux.conf
    - f_config_starship.toml
    - d_redshift
    - d_config_rofi
    - d_config_alacritty
    - d_mpd
    - d_ncmpcpp
    - d_config_polybar
    - d_scripts
    - d_dunst
    - d_config_i3
