# Name : bluloco
colors:
  # Default colors
  primary:
    background: '#282c34'
    foreground: '#abb2bf'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text:   '#282c34'
    cursor: '#ffcc00'

  # Normal colors
  normal:
    black:   '#4a505d'
    red:     '#f81141'
    green:   '#23974a'
    yellow:  '#fd7e57'
    blue:    '#285bff'
    magenta: '#8c62fd'
    cyan:    '#366f9a'
    white:   '#ccd5e5'

  # Bright colors
  bright:
    black:   '#61697a'
    red:     '#fc4a6d'
    green:   '#37bd58'
    yellow:  '#f6be48'
    blue:    '#199ffd'
    magenta: '#fc58f6'
    cyan:    '#50acae'
    white:   '#ffffff'
